name: n1_transaction
description: Premium driver companion UI for N1 TRANSPORTATION.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  config:
    enable-swift-package-manager: false
  generate: true
  assets:
    - assets/images_Logo/
  uses-material-design: true
  fonts:
    - family: KantumruyPro
      fonts:
        - asset: assets/font_khmer/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/font_khmer/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/font_khmer/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/font_khmer/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/font_khmer/KantumruyPro-Bold.ttf
          weight: 700
