name: n1_transaction
description: Premium driver companion UI for N1 TRANSPORTATION.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  config:
    enable-swift-package-manager: false
  generate: true
  assets:
    - assets/images_Logo/
    - assets/image/
  uses-material-design: true
  fonts:
    - family: Battambang
      fonts:
        - asset: assets/font_khmer/Battambang-Thin.ttf
          weight: 100
        - asset: assets/font_khmer/Battambang-Light.ttf
          weight: 300
        - asset: assets/font_khmer/Battambang-Regular.ttf
          weight: 400
        - asset: assets/font_khmer/Battambang-Bold.ttf
          weight: 700
        - asset: assets/font_khmer/Battambang-Black.ttf
          weight: 900
